name: Appsand CI

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Appsand
        run: |
          chmod +x appsand.sh
          sudo ./appsand.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Appsand
          path: appsand.sh
